# Generated by Django 4.2.3 on 2024-04-06 04:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='xabar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matn', models.TextField()),
                ('student_massiv', models.CharField(max_length=255)),
                ('img_manaviy', models.CharField(max_length=255)),
                ('fullname_manaviy', models.CharField(max_length=255)),
                ('tutor_fullname', models.CharField(max_length=255)),
                ('tutor_hemis_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Topshiriq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.CharField(max_length=255)),
                ('fullname', models.CharField(max_length=255)),
                ('talabalar', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Talaba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_manaviy', models.CharField(max_length=255)),
                ('fullname_manaviy', models.CharField(max_length=255)),
                ('tutor_fullname', models.CharField(max_length=255)),
                ('tutor_hemis_id', models.CharField(max_length=255)),
                ('group_id', models.CharField(max_length=255)),
                ('group', models.CharField(max_length=255)),
                ('student_hemis_id', models.CharField(max_length=255)),
                ('img', models.CharField(blank=True, max_length=255)),
                ('student_phone_number_1', models.CharField(blank=True, max_length=255, null=True)),
                ('student_phone_number_2', models.CharField(blank=True, max_length=255, null=True)),
                ('student_telegram', models.CharField(blank=True, max_length=255, null=True)),
                ('location_url', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('xabar_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.xabar')),
            ],
        ),
    ]
